### ISSUE TITLE
Filter excludes media events

### ISSUE THREAD

**Issue by good-idea** [tyv/pick-react-known-prop#5]
Normal attributes: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Attributes
And events: https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

I'm happy to make a PR for this. Adding them to the list is no problem, but there would also need to be the extra step of checking to see if the element is an `<audio>` or `<video>` tag.

Is this overstepping the purpose of this module?

**Comment by tyv** [comment]
thanks for your issue, really good catch! 
I don't think this library should check if element is `video` or `audio`, because this is just filter function. 

html attributes this lib takes from this package https://github.com/alexmingoia/html-attributes, so I think good idea is to update it with audio and video attrs, would be nice if you can add them with PR to that lib (I will create issue).
events  I will add soon.

once again, thanks!
